# 조회
GET http://localhost:3000/maraton

### 생성
POST http://localhost:3000/maraton
Content-Type: application/json

{
    "name": "test1",
    "eventDate": "2024-04-03",
    "eventName": "test event",
    "type": "10K",
    "record": "55:00:00"
}

### Getone 
GET http://localhost:3000/maraton/1

### delete
DELETE http://localhost:3000/maraton/1

### update
PUT http://localhost:3000/maraton/1
Content-Type: application/json

{
    "name": "test1",
    "eventDate": "2024-04-03",
    "eventName": "test event2",
    "type": "10K",
    "record": "55:00:00"
}